import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import {
  ApiError,
  api,
  type ProvenanceDetail,
  type ProvenanceSummary,
} from "../api/client";

/**
 * The page that answers "why should I believe you?".
 *
 * Its one job is a comparison a lawyer can make in under a minute: the clause as
 * published, beside our encoding of it, in the same eyeline. Everything else on
 * the page is subordinate to that — the signature, the inputs and the review
 * notes are all context for a reader who has already made that comparison and
 * wants to know what it rests on.
 *
 * So the two panels sit side by side from `md` upward and stack on a phone with
 * the source text first, because the source is what a reviewer reads against.
 * The encoded steps are generated by the backend from the same band table the
 * evaluator reads; nothing here is written by hand, and there is no path by
 * which this page can describe a rule we do not apply.
 */
export default function Provenance() {
  const { t } = useTranslation();
  const [rules, setRules] = useState<ProvenanceSummary[] | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [detail, setDetail] = useState<ProvenanceDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api
      .provenance()
      .then((listing) => setRules(listing.rules))
      .catch((err: unknown) =>
        setError(err instanceof ApiError ? err.message : t("status.serviceUnavailable")),
      );
  }, [t]);

  useEffect(() => {
    if (selected === null) return;
    let current = true;
    api
      .provenanceDetail(selected)
      .then((body) => {
        if (current) setDetail(body);
      })
      .catch((err: unknown) => {
        if (current)
          setError(err instanceof ApiError ? err.message : t("status.serviceUnavailable"));
      });
    // Guards against a slow first response overwriting a faster second one when
    // a reader clicks twice.
    return () => {
      current = false;
    };
  }, [selected, t]);

  // Whether the loaded detail belongs to the rule currently selected, rather
  // than merely whether some detail is loaded. Opening a second rule while the
  // first is still on screen would otherwise show the first rule's clause under
  // the second rule's heading — a provenance page displaying the wrong
  // provenance, which is the one failure this page cannot have.
  const showing = selected !== null && detail !== null && detail.rule_id === selected;

  if (error) {
    return (
      <p role="alert" className="rounded bg-paper-raised p-3 text-danger">
        {error}
      </p>
    );
  }

  if (rules === null) {
    return <p className="text-ink-500">{t("provenance.loading")}</p>;
  }

  if (showing) {
    return <Detail detail={detail} onBack={() => setSelected(null)} />;
  }

  if (selected !== null) {
    return <p className="text-ink-500">{t("provenance.loading")}</p>;
  }

  return (
    <section aria-labelledby="provenance-heading">
      <h2 id="provenance-heading" className="text-2xl font-semibold text-ink-900">
        {t("provenance.heading")}
      </h2>
      <p className="mt-2 text-ink-700">{t("provenance.intro")}</p>

      {rules.length === 0 ? (
        <p className="mt-6 text-ink-500">{t("provenance.empty")}</p>
      ) : (
        <ul className="mt-6 space-y-3">
          {rules.map((rule) => (
            <li
              key={rule.rule_id}
              className="rounded border border-edge bg-paper-raised p-4"
            >
              <h3 className="font-semibold text-ink-900">{rule.title}</h3>
              <p className="mt-1 text-sm text-ink-700">
                {t("provenance.clause")}: {rule.clause}
              </p>
              <ApprovalBadge status={rule.approval_status} />
              {!rule.signature_matches && (
                <p role="alert" className="mt-2 text-sm text-danger">
                  {t("provenance.signatureMismatch")}
                </p>
              )}
              <button
                type="button"
                onClick={() => setSelected(rule.rule_id)}
                className="mt-3 rounded border border-edge px-3 py-2 text-sm text-ink-900"
              >
                {t("provenance.open")}
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function ApprovalBadge({ status }: { status: ProvenanceSummary["approval_status"] }) {
  const { t } = useTranslation();
  // `provisional` is the honest state and it is stated in words, not as a
  // colour. A reader who sees a signature and an official-looking citation will
  // otherwise assume a lawyer signed this off. Nobody has.
  return (
    <p className="mt-1 text-sm text-ink-700">
      {t("provenance.statusHeading")}: {t(`approval.${status}`)}
    </p>
  );
}

function Detail({
  detail,
  onBack,
}: {
  detail: ProvenanceDetail;
  onBack: () => void;
}) {
  const { t } = useTranslation();

  return (
    <section aria-labelledby="rule-heading">
      <button
        type="button"
        onClick={onBack}
        className="rounded border border-edge px-3 py-2 text-sm text-ink-900"
      >
        {t("provenance.back")}
      </button>

      <h2 id="rule-heading" className="mt-4 text-2xl font-semibold text-ink-900">
        {detail.citation.title}
      </h2>
      <p className="mt-1 text-ink-700">
        {t("provenance.clause")}: {detail.citation.clause}
      </p>
      <p className="mt-1 text-sm text-ink-700">
        {t("provenance.effectiveFrom")}: {detail.effective_from}
      </p>
      <p className="mt-1 text-sm">
        <a href={detail.citation.url} className="text-ink-900 underline">
          {t("provenance.source")}
        </a>
      </p>
      <ApprovalBadge status={detail.approval_status} />

      {/*
        The comparison. Stacked on a phone with the source first, side by side
        from `md`, because reading an encoding against a text is the whole task.
      */}
      <div className="mt-6 grid gap-6 md:grid-cols-2">
        <article>
          <h3 className="font-semibold text-ink-900">
            {t("provenance.sourceHeading")}
          </h3>
          {/*
            `whitespace-pre-wrap`: the decree is a numbered list and its own line
            breaks carry its structure. Collapsing them would make the clause
            harder to read than the paper it came from.
          */}
          <blockquote className="mt-2 whitespace-pre-wrap border-s-4 border-edge ps-3 text-sm text-ink-900">
            {detail.verbatim}
          </blockquote>
        </article>

        <article>
          <h3 className="font-semibold text-ink-900">
            {t("provenance.encodedHeading")}
          </h3>
          <ol className="mt-2 space-y-3">
            {detail.encoded.map((step) => (
              <li
                key={step.step}
                className="rounded border border-rule bg-paper-raised p-3 text-sm"
              >
                <p className="text-ink-900">
                  <span className="font-semibold">{t("provenance.stepCondition")}</span>{" "}
                  {step.condition}
                </p>
                <p className="mt-1 text-ink-900">
                  <span className="font-semibold">{t("provenance.stepOutcome")}</span>{" "}
                  {step.outcome}
                </p>
              </li>
            ))}
          </ol>
        </article>
      </div>

      <h3 className="mt-8 font-semibold text-ink-900">
        {t("provenance.inputsHeading")}
      </h3>
      <ul className="mt-2 space-y-2">
        {detail.inputs.map((input) => (
          <li key={input.name} className="text-sm text-ink-900">
            <span className="tabular">{input.name}</span>
            <span className="text-ink-700">
              {" — "}
              {input.derived
                ? t("provenance.inputDerived")
                : t("provenance.inputStated")}
            </span>
          </li>
        ))}
      </ul>

      {detail.review_notes.length > 0 && (
        <>
          <h3 className="mt-8 font-semibold text-ink-900">
            {t("provenance.notesHeading")}
          </h3>
          <p className="mt-1 text-sm text-ink-700">{t("provenance.notesIntro")}</p>
          <ul className="mt-2 space-y-2">
            {detail.review_notes.map((note) => (
              <li key={note} className="text-sm text-ink-900">
                {note}
              </li>
            ))}
          </ul>
        </>
      )}

      <h3 className="mt-8 font-semibold text-ink-900">
        {t("provenance.signatureHeading")}
      </h3>
      <p className="mt-1 text-sm text-ink-700">
        {t("provenance.signatureExplained")}
      </p>
      {/*
        `break-all`: a sha256 signature is 71 unbroken characters and widens the
        page past the viewport on every phone without it.
      */}
      <p className="mt-2 break-all text-sm text-ink-900 tabular">
        {detail.signature}
      </p>
      <p
        className={`mt-2 text-sm ${detail.signature_matches ? "text-ink-700" : "text-danger"}`}
        role={detail.signature_matches ? undefined : "alert"}
      >
        {detail.signature_matches
          ? t("provenance.signatureMatches")
          : t("provenance.signatureMismatch")}
      </p>
      {detail.computed_signature !== null && (
        <p className="mt-2 break-all text-sm text-danger tabular">
          {t("provenance.computedSignature")}: {detail.computed_signature}
        </p>
      )}
    </section>
  );
}
